### PR TITLE
Add PySide6 GUI for MDD configuration

### PR DESCRIPTION
**Pull request by fhdk**
Introduced a GUI for Manjaro Data Donor using PySide6. Updated `requirements.txt` to include PySide6 and expanded `mdd.py` with GUI components to set options for telemetry and scheduling. Additionally, implemented config file handling and enhanced service configuration methods.

### CODE REVIEW

**Comment by yochananmarqos** [comment]
Looks good so far. The scrollbars look a little out of place, however.

Using QAdwaitaDecorations on GNOME:

Screenshot From 2024-11-10 12-36-44

Using the default Kvantum KvLibadwaitaMaiaDark theme:

Screenshot From 2024-11-10 12-40-09

**Comment by fhdk** [comment]
image

**Comment by yochananmarqos** [comment]
I installed to site-packages, but `mddgui` complains:

```
Traceback (most recent call last):
  File "/usr/bin/mddgui", line 271, in <module>
    run()
  File "/usr/bin/mddgui", line 262, in run
    mdd.prepare_inxi()
    ^^^^^^^^^^^^^^^^
AttributeError: module 'mdd' has no attribute 'prepare_inxi'
```

**Comment by fhdk** [comment]
I suspect the problem is due to the files is lacking the .py extension - the import does not work.
@romangg does not want the GUI to be part of mdd - but a stand alone script - that is why I moved the GUI to a separate file.


The files - if bundled together a different packaging needs to be done in /usr/lib/python3.12/site-packages and a symlink to mdd.py as /usr/bin/mdd

I will close this PR - need to r

**Comment by yochananmarqos** [comment]
Ah, yes it was the file extensions. :man_facepalming: 

With Kvantum, the scrollbars are only visible upon hover.


QAdwaitaDecorations:
image

Kvantum:
Screenshot From 2024-11-12 09-17-55

**Comment by yochananmarqos** [comment]
@fhdk By the way, I do not understand why you closed this. :thinking:

**Comment by fhdk** [comment]
> @fhdk By the way, I do not understand why you closed this

Private feedback from @romangg - also mentioned in out Team Sync

https://github.com/fhdk/mdd/tree/feat-donate-gui

**Pull request closed without merging**
