### PR TITLE
Capture command stderr

### LINKED ISSUE #11: get_audio_info | TypeError: argument of type 'NoneType' is not iterable
A [user](https://forum.manjaro.org/u/D.Dave) posted the following error:

```
Welcome to MDD - The Manjaro Data Donor
Preparing data submission...
Error: "failed to connect: Host is down"
Traceback (most recent call last):
  File "/usr/bin/mdd", line 843, in <module>
    main()
  File "/usr/bin/mdd", line 808, in main
    data = get_device_data(args.telemetry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/mdd", line 753, in get_device_data
    "audio": get_audio_info(),
             ^^^^^^^^^^^^^^^^
  File "/usr/bin/mdd", line 530, in get_audio_info
    "active": 'core.daemon = "true"' in pipew_out and not pulseaudio_active,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

We might need a check for that case too.

### PR DESCRIPTION
**Pull request by romangg**
* Instead of showing it directly on the terminal.
* Fixes an exception on pw-cli call failing.

Closes #11

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Seems to create the following error:

```
File "/usr/bin/mdd", line 68
    except subprocess.CalledProcessError as e:
                                              ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by romangg** [comment]
Works for me.

**Comment by philmmanjaro** [comment]
Maybe the user doesn't know on how to apply the patch. He posted the error in the forums.

**Comment by romangg** [comment]
I'll merge now as it works for me fine and the user can then test again once it hits repos without having to apply the patch manually.

**Pull request merged**
